#ifndef CONFIG_H_
#define CONFIG_H_
#include "stdint.h"

#define DISPLAY_TYPE_M365DASHBOARD (1<<1)
#define DISPLAY_TYPE_DEBUG (1<<0)

#define TRIGGER_OFFSET_ADC 50
#define TRIGGER_DEFAULT 2020
#define _T 2028
#define SPEEDFILTER 3

#define DISPLAY_TYPE DISPLAY_TYPE_M365DASHBOARD

#define CAL_BAT_V 14
#define CAL_I 38

#define P_FACTOR_I_Q 100
#define I_FACTOR_I_Q 2
#define P_FACTOR_I_D 100
#define I_FACTOR_I_D 10

#define THROTTLEOFFSET 45
#define THROTTLEMAX 175
#define BRAKEOFFSET 50
#define BRAKEMAX 190

#define WHEEL_CIRCUMFERENCE 2302
#define GEAR_RATIO 1

#define SPEEDLIMIT_ECO 20
#define SPEEDLIMIT_NORMAL 35
#define SPEEDLIMIT_SPORT 50

#define PH_CURRENT_MAX_ECO 10000
#define PH_CURRENT_MAX_NORMAL 15000
#define PH_CURRENT_MAX_SPORT 25000

#define REGEN_CURRENT 10000
#define FW_CURRENT_MAX 0

#define BATTERYCURRENT_MAX 20000
#define REGEN_CURRENT_MAX 1000

#define BATTERYVOLTAGE_MIN 33000
#define BATTERYVOLTAGE_MAX 54600

#define REVERSE -1

#define SPEED_PLL 0
#define P_FACTOR_PLL 10
#define I_FACTOR_PLL 10

#endif
