name: Build M365 V3

on:
  push:
    branches: [patch-2]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install ARM GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi

    - name: Build
      run: make

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Prepare firmware ZIP
      run: python tools/xiaotea/Scripts/prepareZip_online.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        path: ${{ github.workspace }}/tools/zip_output
        name: M365_v3_build_${{ github.run_number }}
        retention-days: 5
typedef struct {
  q31_t Voltage;
  int16_t phase_current_limit;
  q31_t Battery_Current;
  uint8_t hall_angle_detect_flag;
  uint8_t char_dyn_adc_state;
  uint8_t assist_level;
  uint8_t regen_level;
  int8_t Temperature;
  int8_t mode;
  bool light;
  bool beep;
  uint8_t shutdown;
  q31_t i_q_setpoint;
  int32_t i_q_setpoint_target;
  uint32_t speed;
  int8_t speed_limit;
} M365State_t;

int32_t map(int32_t x, int32_t in_min, int32_t in_max, int32_t out_min,
        int32_t out_max);

extern q31_t switchtime[3];
extern uint32_t uint32_PAS_counter;

void UserSysTickHandler();

void calculate_tic_limits(int8_t speed_limit);

void _Error_Handler(char*, int);

/* USER CODE END Private defines */

#ifdef __cplusplus
}
#endif

#endif /* __MAIN_H */

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
