name: C/C++ CI

on:
  push:
    branches: [patch-1]
  pull_request:
    branches: [patch-1]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hämta källkoden
        uses: actions/checkout@v4

      - name: Installera ARM-kompilator
        uses: fiam/arm-none-eabi-gcc@v1.0.2
        with:
          release: '9-2020-q2'

      - name: Bygg firmware
        run: make

      - name: Installera Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Skapa Xiaomi ZIP
        run: python tools/xiaotea/Scripts/prepareZip_online.py

      - name: Ladda upp firmware
        uses: actions/upload-artifact@v4
        with:
          path: tools/zip_output
          name: M365_SENSORLESS_PRO_${{ github.run_number }}
          retention-days: 5
